version: '3'

services:

  # Nginx web server acting as a reverse proxy for "web" and "api" services
  nginx:
    image: nginx:1.13.3-alpine
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/log/nginx
      - /var/run
    depends_on:
      - api
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./config/nginx-snippets:/etc/nginx/snippets:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  # Data API and authentication/authorization
  api:
    image: node:8.4.0-alpine
    hostname: api
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    expose:
      - "8080"
    ports:
      - "127.0.0.1:9229:9229" # V8 inspector for tools/run.js
      - "127.0.0.1:9230:9230" # V8 inspector for src/server.js
    volumes:
      - yarn:/root/.cache/yarn
      - ./:/usr/src/app
    user: node
    working_dir: /usr/src/app
    command: node tools/run.js # or, `node --inspect=0.0.0.0:9229 tools/run.js`

  # Distributed in-memory cache
  redis:
    image: redis:4.0.1-alpine
    read_only: true
    volumes:
      - redis:/data
    user: redis

volumes:
  redis:
  yarn:
